# Generated by Django 2.1.7 on 2019-03-20 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domicile',
            fields=[
                ('residence_id', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=100)),
                ('price', models.FloatField(max_length=10)),
                ('residence_type', models.CharField(max_length=50)),
                ('size', models.CharField(max_length=15)),
                ('pet_friendly', models.BooleanField()),
                ('pets_allowed', models.CharField(blank=True, max_length=100, null=True)),
                ('limit_tenant_count', models.IntegerField(blank=True, null=True)),
                ('current_tenant_count', models.IntegerField(blank=True, null=True)),
                ('amenities', models.CharField(blank=True, max_length=100, null=True)),
                ('utilities_included_rent', models.BooleanField()),
                ('coordinates', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UnverifiedUser',
            fields=[
                ('username', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField(max_length=10)),
                ('physical_address', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(max_length=100)),
                ('profile_picture', models.ImageField(upload_to='tmp/uploads')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VerifiedUser',
            fields=[
                ('username', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField(max_length=10)),
                ('physical_address', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(max_length=100)),
                ('profile_picture', models.ImageField(upload_to='tmp/uploads')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('verifieduser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='demo.VerifiedUser')),
            ],
            options={
                'db_table': 'admin_users',
            },
            bases=('demo.verifieduser',),
        ),
        migrations.CreateModel(
            name='Landlord',
            fields=[
                ('verifieduser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='demo.VerifiedUser')),
                ('agency', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'landlord_users',
            },
            bases=('demo.verifieduser',),
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('residence', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='demo.Domicile')),
                ('tenants', models.CharField(max_length=100)),
                ('owner', models.CharField(max_length=15)),
                ('owners', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='StarTenant',
            fields=[
                ('verifieduser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='demo.VerifiedUser')),
            ],
            options={
                'db_table': 'star_tenant_users',
            },
            bases=('demo.verifieduser',),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('verifieduser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='demo.VerifiedUser')),
            ],
            options={
                'db_table': 'student_users',
            },
            bases=('demo.verifieduser',),
        ),
    ]
