# Generated by Django 2.1.7 on 2019-03-20 06:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_auto_20190319_2338'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Listing',
            new_name='ActiveListing',
        ),
        migrations.RemoveField(
            model_name='disableduser',
            name='id',
        ),
        migrations.AddField(
            model_name='disableduser',
            name='deletion_time',
            field=models.DateField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='disableduser',
            name='email',
            field=models.EmailField(default='default@example.net', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='disableduser',
            name='secret_key',
            field=models.CharField(default='secret_key', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='disableduser',
            name='username',
            field=models.CharField(default='username', max_length=15, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unverifieduser',
            name='creation_time',
            field=models.DateField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='verifieduser',
            name='creation_time',
            field=models.DateField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterModelTable(
            name='activelisting',
            table='active_listings',
        ),
        migrations.AlterModelTable(
            name='disableduser',
            table='disabled_users',
        ),
    ]
