# Generated by Django 2.1.7 on 2019-04-21 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0003_auto_20190420_2025'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='expiredlisting',
            table=None,
        ),
        migrations.AlterModelTable(
            name='validlisting',
            table=None,
        ),
    ]
