# Generated by Django 2.1.7 on 2019-03-21 05:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0003_auto_20190319_2357'),
    ]

    operations = [
        migrations.AddField(
            model_name='domicile',
            name='creation_time',
            field=models.DateField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='domicile',
            name='photo',
            field=models.ImageField(default=-1, upload_to='demo/residence_pictures'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='unverifieduser',
            name='profile_picture',
            field=models.ImageField(upload_to='demo/profile_pictures'),
        ),
        migrations.AlterField(
            model_name='verifieduser',
            name='profile_picture',
            field=models.ImageField(upload_to='demo/profile_pictures'),
        ),
    ]
