# Generated by Django 2.1.7 on 2019-04-21 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0004_auto_20190420_2026'),
    ]

    operations = [
        #migrations.RemoveField(
        #    model_name='expiredlisting',
        #    name='residence',
        #),
        #migrations.RemoveField(
        #    model_name='validlisting',
        #    name='residence',
        #),
        #migrations.DeleteModel(
        #    name='ExpiredListing',
        #),
        #migrations.DeleteModel(
        #    name='ValidListing',
        #),
    ]
