# Generated by Django 2.1.7 on 2019-03-21 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0004_auto_20190320_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='unverifieduser',
            name='first_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='unverifieduser',
            name='last_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='verifieduser',
            name='first_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='verifieduser',
            name='last_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
