# Generated by Django 2.1.7 on 2019-04-21 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0005_auto_20190420_2032'),
    ]

    operations = [
        #migrations.AlterModelTable(
        #    name='expiredlisting',
        #    table='expired_listings',
        #),
    ]
