# Generated by Django 2.1.7 on 2019-03-21 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0005_auto_20190320_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domicile',
            name='residence_type',
            field=models.CharField(choices=[('apartment', 'Apartment'), ('house', 'House'), ('room', 'Room'), ('garage', 'Garage'), ('in_law_unit', 'In-Law Unit'), ('other', 'Other')], max_length=50),
        ),
    ]
