# Generated by Django 2.1.7 on 2019-04-21 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0007_auto_20190420_2039'),
    ]

    operations = []
