# Generated by Django 2.1.7 on 2019-04-16 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0008_auto_20190324_2205'),
    ]

    operations = [
        migrations.RenameField(
            model_name='domicile',
            old_name='zip',
            new_name='zip_code',
        ),
        migrations.RemoveField(
            model_name='domicile',
            name='amenities',
        ),
        migrations.RemoveField(
            model_name='domicile',
            name='coordinates',
        ),
        migrations.RemoveField(
            model_name='domicile',
            name='current_tenant_count',
        ),
        migrations.RemoveField(
            model_name='domicile',
            name='description',
        ),
        migrations.RemoveField(
            model_name='domicile',
            name='limit_tenant_count',
        ),
        migrations.RemoveField(
            model_name='domicile',
            name='pet_friendly',
        ),
        migrations.RemoveField(
            model_name='domicile',
            name='pets_allowed',
        ),
        migrations.RemoveField(
            model_name='domicile',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='domicile',
            name='utilities_included_rent',
        ),
        migrations.AddField(
            model_name='activelisting',
            name='amenities',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='activelisting',
            name='coordinates',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='activelisting',
            name='current_tenant_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activelisting',
            name='description',
            field=models.TextField(default=90210),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activelisting',
            name='limit_tenant_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activelisting',
            name='pet_friendly',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activelisting',
            name='pets_allowed',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='activelisting',
            name='photo',
            field=models.ImageField(default='null', upload_to='demo/residence_pictures'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activelisting',
            name='utilities_included_rent',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unverifieduser',
            name='bio',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='unverifieduser',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='unverifieduser',
            name='is_student',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unverifieduser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='unverifieduser',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='unverifieduser',
            name='zip_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='verifieduser',
            name='bio',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='verifieduser',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='verifieduser',
            name='is_student',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='verifieduser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='verifieduser',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='verifieduser',
            name='zip_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
