# Generated by Django 2.1.7 on 2019-04-21 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0008_auto_20190420_2041'),
    ]

    operations = []
