# Generated by Django 2.1.7 on 2019-04-21 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0009_auto_20190420_2043'),
    ]

    operations = []
