# Generated by Django 2.1.7 on 2019-04-16 22:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0009_auto_20190416_1539'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('creation_time', models.DateField(default=django.utils.timezone.now, editable=False)),
                ('text', models.CharField(max_length=500)),
                ('poster', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='demo.VerifiedUser')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
