# Generated by Django 2.1.7 on 2019-04-21 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0010_auto_20190420_2045'),
    ]

    operations = []
