# Generated by Django 2.1.7 on 2019-04-18 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0011_auto_20190416_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='unverifieduser',
            name='cleanliness',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unverifieduser',
            name='partiness',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unverifieduser',
            name='socialness',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='verifieduser',
            name='cleanliness',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='verifieduser',
            name='partiness',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='verifieduser',
            name='socialness',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
