# Generated by Django 2.1.7 on 2019-04-21 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0011_auto_20190420_2046'),
    ]

    operations = [
        #migrations.RemoveField(
        #    model_name='expiredlisting',
        #    name='residence',
        #),
        #migrations.RemoveField(
        #    model_name='expiredlistings',
        #    name='residence',
        #),
        #migrations.RemoveField(
        #    model_name='validlisting',
        #    name='residence',
        #),
        #migrations.RemoveField(
        #    model_name='validlistings',
        #    name='residence',
        #),
        migrations.AlterModelTable(
            name='comment',
            table='snn_comments',
        ),
        migrations.AlterModelTable(
            name='message',
            table='snn_messages',
        ),
        migrations.AlterModelTable(
            name='page',
            table='snn_page',
        ),
        migrations.AlterModelTable(
            name='post',
            table='snn_posts',
        ),
        #migrations.DeleteModel(
        #    name='ExpiredListing',
        #),
        #migrations.DeleteModel(
        #    name='ExpiredListings',
        #),
        #migrations.DeleteModel(
        #    name='ValidListing',
        #),
        #migrations.DeleteModel(
        #    name='ValidListings',
        #),
    ]
