# Generated by Django 2.1.7 on 2019-04-18 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0012_auto_20190417_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unverifieduser',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='demo/profile_pictures'),
        ),
        migrations.AlterField(
            model_name='verifieduser',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='demo/profile_pictures'),
        ),
    ]
