# Generated by Django 2.1.7 on 2019-04-21 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0013_auto_20190420_2053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='poster',
        ),
        migrations.RemoveField(
            model_name='message',
            name='poster',
        ),
        migrations.RemoveField(
            model_name='message',
            name='recipient',
        ),
        migrations.DeleteModel(
            name='Page',
        ),
        migrations.RemoveField(
            model_name='post',
            name='poster',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
