# Generated by Django 2.1.7 on 2019-04-21 03:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0014_auto_20190420_2054'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('creation_time', models.DateField(default=django.utils.timezone.now, editable=False)),
                ('text', models.CharField(max_length=500)),
                ('poster', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='comment_poster_id', serialize=False, to='demo.VerifiedUser', to_field='username')),
            ],
            options={
                'db_table': 'snn_comments',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('creation_time', models.DateField(default=django.utils.timezone.now, editable=False)),
                ('text', models.CharField(max_length=500)),
                ('poster', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='message_poster_id', serialize=False, to='demo.VerifiedUser', to_field='username')),
            ],
            options={
                'db_table': 'snn_messages',
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('owners', models.CharField(max_length=500)),
                ('members', models.CharField(blank=True, max_length=500, null=True)),
                ('posts', models.CharField(blank=True, max_length=500, null=True)),
                ('location', models.CharField(max_length=500)),
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'snn_page',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('creation_time', models.DateField(default=django.utils.timezone.now, editable=False)),
                ('text', models.CharField(max_length=500)),
                ('poster', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='post_poster_id', serialize=False, to='demo.VerifiedUser', to_field='username')),
            ],
            options={
                'db_table': 'snn_posts',
            },
        ),
        migrations.AddField(
            model_name='message',
            name='recipient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recipient_id', to='demo.VerifiedUser', to_field='username'),
        ),
    ]
