# Generated by Django 2.1.7 on 2019-04-21 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0016_expiredlisting_validlisting'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='page',
            table='snn_pages',
        ),
    ]
