# Generated by Django 2.1.7 on 2019-04-21 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0017_auto_20190420_2057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='location',
        ),
        migrations.RemoveField(
            model_name='page',
            name='posts',
        ),
        #migrations.AddField(
        #    model_name='comment',
        #    name='comment_id',
        #    field=models.IntegerField(default=0, primary_key=True, serialize=False),
        #    preserve_default=False,
        #),
        migrations.AddField(
            model_name='message',
            name='message_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='post_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        #migrations.AlterField(
        #    model_name='comment',
        #    name='poster',
        #    field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='comment_poster_id', to='demo.VerifiedUser', to_field='username'),
        #),
        migrations.AlterField(
            model_name='message',
            name='poster',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='message_poster_id', to='demo.VerifiedUser', to_field='username'),
        ),
        migrations.AlterField(
            model_name='post',
            name='poster',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='post_poster_id', to='demo.VerifiedUser', to_field='username'),
        ),
    ]
