# Generated by Django 2.1.7 on 2019-04-21 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0018_auto_20190420_2122'),
    ]

    operations = [
        #migrations.RemoveField(
        #    model_name='comment',
        #    name='poster',
        #),
    ]
