# Generated by Django 2.1.7 on 2019-04-21 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0019_remove_comment_poster'),
    ]

    operations = [
        #migrations.RemoveField(
        #    model_name='comment',
        #    name='poster',
        #),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
