# Generated by Django 2.1.7 on 2019-04-21 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0021_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='poster',
        ),
        migrations.RemoveField(
            model_name='message',
            name='poster',
        ),
        migrations.RemoveField(
            model_name='message',
            name='recipient',
        ),
        migrations.RemoveField(
            model_name='post',
            name='poster',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
