# Generated by Django 2.1.7 on 2019-04-21 04:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0022_auto_20190420_2129'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('creation_time', models.DateField(default=django.utils.timezone.now, editable=False)),
                ('text', models.CharField(max_length=500)),
                ('comment_id', models.IntegerField(primary_key=True, serialize=False)),
                ('poster', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='comment_poster_id', to='demo.VerifiedUser', to_field='username')),
            ],
            options={
                'db_table': 'snn_comments',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('creation_time', models.DateField(default=django.utils.timezone.now, editable=False)),
                ('text', models.CharField(max_length=500)),
                ('message_id', models.IntegerField(primary_key=True, serialize=False)),
                ('poster', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='message_poster_id', to='demo.VerifiedUser', to_field='username')),
                ('recipient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recipient_id', to='demo.VerifiedUser', to_field='username')),
            ],
            options={
                'db_table': 'snn_messages',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('creation_time', models.DateField(default=django.utils.timezone.now, editable=False)),
                ('text', models.CharField(max_length=500)),
                ('post_id', models.IntegerField(primary_key=True, serialize=False)),
                ('poster', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='post_poster_id', to='demo.VerifiedUser', to_field='username')),
            ],
            options={
                'db_table': 'snn_posts',
            },
        ),
    ]
