# Generated by Django 2.1.7 on 2019-05-06 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0023_comment_message_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='domicile',
            name='bath_count',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='domicile',
            name='bed_count',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
